# move this file in workflows folder
# this template is here to avoid future issues on my main account

name: Proxy List Updater

on:
  schedule:
    - cron: "*/30 * * * *" # Runs at the start of 30 mins
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Update proxies
        run: python proxies.py

      - name: Commit changes
        run: |
          git config --global user.name "0xArchit"
          git config --global user.email "0xarchit@gmail.com"
          git add .
          git commit -m "Updated ➠ $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
          git push
